### ISSUE TITLE
run demo error 

### ISSUE THREAD

**Issue by leon-liangwu** [nilboy/tensorflow-yolo#46]
I just want to try the demo, but I got this. Can anyone help me ?
2018-02-22 11:17:41.099700: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-02-22 11:17:41.099982: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1208] Found device 0 with properties: 
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:01:00.0
totalMemory: 3.94GiB freeMemory: 3.33GiB
2018-02-22 11:17:41.100000: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1308] Adding visible gpu devices: 0
2018-02-22 11:17:41.547405: I tensorflow/core/common_runtime/gpu/gpu_device.cc:989] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2985 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "demo.py", line 77, in <module>
    saver.restore(sess, 'models/pretrain/yolo_tiny.ckpt')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1751, in restore
    " to the checkpoint files." % save_path)
**ValueError: The specified path: models/pretrain/yolo_tiny.ckpt is a file. Please specify only the path prefix to the checkpoint files.**

**Comment by PeterJaq** [comment]
Do you download yolo_tiny.ckpt by you self?

**Comment by leon-liangwu** [comment]
yes of course.
