### ISSUE TITLE
ModuleNotFoundError: No module named 'dataset'

### ISSUE THREAD

**Issue by guptakvgaurav** [nilboy/tensorflow-yolo#69]
Python interpreter is not able to resolve the dataset module and this leads to the following error.

```
 python tools/train.py -c conf/train.cfg
Traceback (most recent call last):
  File "tools/train.py", line 6, in <module>
    import yolo
  File "./yolo/__init__.py", line 1, in <module>
    import dataset
ModuleNotFoundError: No module named 'dataset'

```
I am running it under Anaconda environment where I have Tensorflow-gpu installed.
```
python --version
Python 3.6.5 :: Anaconda, Inc.

```

**Comment by guptakvgaurav** [comment]
It was due to python version as there is a change in usage of import from python 2 to python 3.

To fix it just change the relative imports to absolute import. Ex: 
```
import dataset
import net
import solver

```
should change to 

```
import yolo.dataset
import yolo.net
import yolo.solver

```
